KEYWORDS = [
    "machine learning",
    "artificial intelligence",
    "data science",
    "llm",
    "generative ai",
    "gen ai",
    "genai",
    "automation",
    "automate",
    "robotics",
    "programming",
    "engineer",
    "mlops",
    "pytorch",
    "neural network",
    "deep learning",
    "large language models",
    "time series",
    "self-supervised learning",
    "tensorflow",
    "hugging face",
    "transformer model",
    "gpt",
    "google gemini",
    "deepmind",
    "image classification",
    "reinforcement learning",
    "pre-trained model",
    "neural text",
    "open ai",
    "openai",
    "image recognition",
    "speech recognition",
    "cuda",
    "jax",
    "keras",
    "machine intelligence",
    "google brain",
    "numpy",
    "diffusion model",
    "transformer block",
    "convolution block",
    "attention layer",
    "feed-forward layer",
    "unet",
    "text-to-image",
    "stable diffusion",
    "autoencoder",
    "collaborative filtering",
    "neural recommender",
]
